### PR TITLE
Refactor package layout

### PR DESCRIPTION
**Pull request by neoglez**
Refactor package layout and add namespace smplpytorch to imports. The namespace smpl is too general and could conflict with the model itself.

### CODE REVIEW

**Comment by gulvarol** [comment]
Thanks for the improvements. I agree that the name can conflict with the original version. However, the nested `smpl` folder seems unnecessary. I was thinking just to rename `smpl` to `smplpytorch`. I will change the repository name to smplpytorch and remove dashes/underscores etc if you don't mind. Also, why did you remove torch and chumpy from the requirements?

**Comment by neoglez** [comment]
> However, the nested smpl folder seems unnecessary. I was thinking just to rename smpl to smplpytorch

Great idea.
> I will change the repository name to smplpytorch and remove dashes/underscores etc.

We don't have to. As long as we build the package with the name smplpytorch it's ok (as it is at the moment: https://pypi.org/project/smpl-pytorch/). Changing the repo might be confusing for others.

> Also, why did you remove torch and chumpy from the requirements?

Since we should try moving to (at least) some stable 0.1.x version, this phase is dev-intense, which makes the torch dependency unpractical if you have to create env/dev env. but, of course, you can add it if you consider it important. Regarding the "external" deped. on chumpy, the "official" release from M. Loper (https://pypi.org/project/chumpy/) does not support py 3.x and PyPi does not (unfortunately) allow git (https://github.com/pypa/pip/issues/3610). You can test it yourself as i made you package owner: https://pypi.org/project/smpl-pytorch/. Nevertheless, it should NOT be a problem to add those dependencies at a later (more mature) moment.

**Comment by gulvarol** [comment]
Thanks for pointing out that PyPi does not work with git. I didn't know, I added a note on readme. Assuming that not many people use this package, I have changed it to smplpytorch. Creating from scratch on pypi might be useful.

**Comment by neoglez** [comment]
Thanks for answering the PRs so fast and being open for contributions :)
I will clone this repo and rebuild on PyPi
This PR is no longer needed.

**Pull request closed without merging**
